-- Open Terminal

sudo mariadb

CREATE DATABASE IF NOT EXISTS flights;

use flights;

DROP TABLE IF EXISTS innodb;

CREATE TABLE innodb (
   YEAR_ SMALLINT NOT NULL,
   MONTH_ TINYINT NOT NULL,
   DAY_OF_MONTH TINYINT NOT NULL,
   DAY_OF_WEEK TINYINT NOT NULL,
   OP_UNIQUE_CARRIER varchar(5) NOT NULL,
   ORIGIN_CITY_NAME varchar(30) NOT NULL, 
   ORIGIN_STATE_ABR varchar(30) NOT NULL, 
   DEST_CITY_NAME varchar(30) NOT NULL, 
   DEST_STATE_ABR varchar(30) NOT NULL, 
   CRS_DEP_TIME TIME,
   DEP_DELAY_NEW SMALLINT,
   CRS_ARR_TIME TIME,
   ARR_DELAY_NEW SMALLINT,
   CANCELLED BOOLEAN,
   CANCELLATION_CODE varchar(1),
   AIR_TIME SMALLINT,
   DISTANCE SMALLINT
) DEFAULT CHARSET=utf8;

show tables;

-- Import CSV
LOAD DATA LOCAL INFILE '/root/flights.csv' INTO TABLE innodb 
   FIELDS TERMINATED BY ',' 
   LINES TERMINATED BY '\r\n'
   (YEAR_, MONTH_, DAY_OF_MONTH, DAY_OF_WEEK, OP_UNIQUE_CARRIER, ORIGIN_CITY_NAME, ORIGIN_STATE_ABR, DEST_CITY_NAME, DEST_STATE_ABR, CRS_DEP_TIME, DEP_DELAY_NEW, CRS_ARR_TIME, ARR_DELAY_NEW, CANCELLED, CANCELLATION_CODE, AIR_TIME, DISTANCE);


